language: python

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install pip --upgrade
  - pip install pyside2==5.11 pytest pytest-qt flake8

before_script: rm --recursive --force --verbose *.py[cod]

script: ./run-tests.sh

stages:
 - lint
 - test

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - stage: lint
      python: 3.6
      script: flake8 quring
